name: Firebase Deploy

on:
  push:
    branches:
      - main  # or the branch you want to deploy (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can adjust the version if needed

      - name: Install dependencies
        run: |
          npm install

      - name: Build and deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm run build  # You can adjust this if you have specific build steps
          firebase deploy --only hosting
